export const CHARACTER_PROFILES = [
  {
    id: 'master-user',
    key: 'master',
    username: 'master',
    displayName: 'Master',
    role: 'master',
    imageUrl: '/media/images/master.jpeg',
    spawnToken: false,
    spawnPosition: null,
    initiativeModifier: 0,
    initiativeMode: 'normal',
    movement: null,
    movementCells: null,
    darkvision: null,
  },
  {
    id: 'player-ilthar',
    key: 'ilthar',
    username: 'ilthar',
    displayName: 'Ilthar Neramyst',
    role: 'adventurer',
    imageUrl: '/media/images/ilthar.jpeg',
    spawnToken: true,
    spawnPosition: { x: 2, y: 4 },
    initiativeModifier: 3,
    initiativeMode: 'normal',
    movement: '9 m (30 ft)',
    movementCells: 6,
    darkvision: 'Scurovisione superiore 36 m (120 ft)',
  },
  {
    id: 'player-thalendir',
    key: 'thalendir',
    username: 'thalendir',
    displayName: 'Thalendir',
    role: 'adventurer',
    imageUrl: '/media/images/thalendir.jpeg',
    spawnToken: true,
    spawnPosition: { x: 4, y: 4 },
    initiativeModifier: 2,
    initiativeMode: 'normal',
    movement: '9 m (30 ft)',
    movementCells: 6,
    darkvision: 'Scurovisione',
  },
  {
    id: 'player-ragnar',
    key: 'ragnar',
    username: 'ragnar',
    displayName: 'Ragnar',
    role: 'adventurer',
    imageUrl: '/media/images/ragnar.jpeg',
    spawnToken: true,
    spawnPosition: { x: 6, y: 4 },
    initiativeModifier: 2,
    initiativeMode: 'advantage',
    movement: '12 m (40 ft)',
    movementCells: 8,
    darkvision: null,
  },
  {
    id: 'player-hunter',
    key: 'hunter',
    username: 'hunter',
    displayName: 'Hunter',
    role: 'adventurer',
    imageUrl: '/media/images/hunter.jpeg',
    spawnToken: true,
    spawnPosition: { x: 8, y: 4 },
    initiativeModifier: 3,
    initiativeMode: 'normal',
    movement: '9 m, anche su muri e soffitti',
    movementCells: 6,
    darkvision: '18 m (60 ft)',
  },
  {
    id: 'player-sylas',
    key: 'sylas',
    username: 'sylas',
    displayName: 'Sylas Elveris',
    role: 'adventurer',
    imageUrl: '/media/images/sylas.jpeg',
    spawnToken: true,
    spawnPosition: { x: 10, y: 4 },
    initiativeModifier: 3,
    initiativeMode: 'normal',
    movement: '9 m (30 ft)',
    movementCells: 6,
    darkvision: '18 m (60 ft)',
  },
  {
    id: 'player-vesuth',
    key: 'vesuth',
    username: 'vesuth',
    displayName: 'Vesuth Ronavior',
    role: 'adventurer',
    imageUrl: '/media/images/vesuth.png',
    spawnToken: true,
    spawnPosition: { x: 12, y: 4 },
    initiativeModifier: 2,
    initiativeMode: 'normal',
    movement: '9 m',
    movementCells: 6,
    darkvision: 'Nessuna',
  },
];

export function findCharacterProfileByUsername(username) {
  const normalized = String(username).trim().toLowerCase();
  return CHARACTER_PROFILES.find((profile) => profile.username === normalized) ?? null;
}

export function findCharacterProfileById(id) {
  return CHARACTER_PROFILES.find((profile) => profile.id === id) ?? null;
}
